input:
  # http_server:
  #   address: ":8080"
  #   path: /post
  #   ws_path: /post/ws
  #   allowed_verbs:
  #     - POST
  #   timeout: 5s
  #   rate_limit: ""
  #   sync_response:
  #     status: "200"
  crdb_changefeed:
    dsn: postgresql://dan:thisisabadpassword@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Dportly-impala-2852
    tables:
      - strm_2
    options:
      - UPDATED
      - CURSOR='1639358944436243506.0000000000'

logger:
  prefix: benthos
  level: DEBUG
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos

output:
  label: ""
  stdout:
    codec: lines
