input:
  file:
    paths: ["input.csv"]
    codec: lines

pipeline:
  processors:
    - log:
        message: ${! json() }

output:
  gcp_bigquery:
    project: benthos-project-test
    dataset: test
    table: table-test
    batching:
      count: 1