version: '3.3'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda
    ports:
      - 8081:8081
    command:
      - 'redpanda start'
      - '--smp 1'
      - '--overprovisioned'
      - '--kafka-addr 0.0.0.0:9092'
      - '--advertise-kafka-addr redpanda:9092'
      - '--pandaproxy-addr 0.0.0.0:8082'
      - '--advertise-pandaproxy-addr redpanda:8082'

  connect-in:
    image: ghcr.io/redpanda-data/connect
    command: [ '-w', '-c', '/connect.yaml' ]
    volumes:
      - ./in.yaml:/connect.yaml

  connect-out:
    image: ghcr.io/redpanda-data/connect
    command: [ '-w', '-c', '/connect.yaml' ]
    volumes:
      - ./out.yaml:/connect.yaml
