http:
  address: :4195
  debug_endpoints: true

input:
  bloblang:
    interval: "1ms"
    mapping: |
      root = {
        "locations": [
          {"name": "Seattle", "state": "WA"},
          {"name": "New York", "state": "NY"},
          {"name": "Bellevue", "state": "WA"},
          {"name": "Olympia", "state": "WA"}
        ]
      }

buffer:
  memory:
    limit: 524288000
    batch_policy:
      enabled: true
      count: 10

pipeline:
  threads: 2
  processors:
    - resource: with_bloblang
    # - resource: with_jq
    # - resource: with_jmespath
    - catch:
      - log:
          message: "Err: ${! error() }"
    - bloblang: 'root = deleted()'

output:
  type: drop

resources:
  processors:
    with_bloblang:
      bloblang: '{"Cities":this.locations.filter(this.state == "WA").map_each(this.name).sort().join(", ")}'

    with_jq:
      jq:
        query: '{Cities: .locations | map(select(.state == "WA").name) | sort | join(", ") }'

    with_jmespath:
      jmespath:
        query: "locations[?state == 'WA'].name | sort(@) | {Cities: join(', ', @)}"

metrics:
  prometheus:
    prefix: benthos
    path_mapping: ""

tracer:
  jaeger:
    agent_address: 'jaeger:6831'